# Generated by Django 4.2.6 on 2024-11-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='audio_url',
        ),
    ]
