# Generated by Django 4.2.6 on 2024-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclosacademia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='courses/img/'),
        ),
    ]
