# Generated by Django 4.2.6 on 2024-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_ciclosacademia_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['title'], 'verbose_name': 'Capítulos', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='order',
        ),
        migrations.AddField(
            model_name='chapter',
            name='url_recursos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='courses/img/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio'),
        ),
    ]
