# Generated by Django 4.2.6 on 2024-11-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_options_remove_chapter_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Capítulos', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='url_recursos',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
