# Generated by Django 4.2.6 on 2024-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_options_remove_chapter_url_recursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='url_recursos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(),
        ),
    ]
